id: P0951E006
initial_creation_type: ocr
source_metadata:
  volumes:
    22f68b13974047229748d3c6355ad0ed:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: ཐུགས་རྗེ་ཆེན་པོ་ལ་སྨྲེ་སྔགས་ཀྱིས་བསྟོད་པ་བྱིན་རླབས་ཅན།
      total_pages: 1379
      volume_number: 37
